INSERT INTO ebpf_audit_db_a1.identity_audit_case (id, k, c) VALUES (1, 10, 'tenant_a_root_db_a1_insert');
SELECT id, k, c FROM ebpf_audit_db_a1.identity_audit_case WHERE id = 1;
UPDATE ebpf_audit_db_a1.identity_audit_case SET k = 11, c = 'tenant_a_root_db_a1_update' WHERE id = 1;
DELETE FROM ebpf_audit_db_a1.identity_audit_case WHERE id = 1;
INSERT INTO ebpf_audit_db_a2.identity_audit_case (id, k, c) VALUES (1, 20, 'tenant_a_root_db_a2_insert');
SELECT id, k, c FROM ebpf_audit_db_a2.identity_audit_case WHERE id = 1;
UPDATE ebpf_audit_db_a2.identity_audit_case SET k = 21, c = 'tenant_a_root_db_a2_update' WHERE id = 1;
DELETE FROM ebpf_audit_db_a2.identity_audit_case WHERE id = 1;
INSERT INTO ebpf_audit_db_a1.identity_audit_case (id, k, c) VALUES (2, 30, 'tenant_a_user_db_a1_insert');
SELECT id, k, c FROM ebpf_audit_db_a1.identity_audit_case WHERE id = 2;
UPDATE ebpf_audit_db_a1.identity_audit_case SET k = 31, c = 'tenant_a_user_db_a1_update' WHERE id = 2;
DELETE FROM ebpf_audit_db_a1.identity_audit_case WHERE id = 2;
INSERT INTO ebpf_audit_db_a2.identity_audit_case (id, k, c) VALUES (2, 40, 'tenant_a_user_db_a2_insert');
SELECT id, k, c FROM ebpf_audit_db_a2.identity_audit_case WHERE id = 2;
UPDATE ebpf_audit_db_a2.identity_audit_case SET k = 41, c = 'tenant_a_user_db_a2_update' WHERE id = 2;
DELETE FROM ebpf_audit_db_a2.identity_audit_case WHERE id = 2;
INSERT INTO ebpf_audit_db_a1.identity_audit_case (id, k, c) VALUES (3, 50, 'tenant_a_proxy_db_a1_insert');
SELECT id, k, c FROM ebpf_audit_db_a1.identity_audit_case WHERE id = 3;
UPDATE ebpf_audit_db_a1.identity_audit_case SET k = 51, c = 'tenant_a_proxy_db_a1_update' WHERE id = 3;
DELETE FROM ebpf_audit_db_a1.identity_audit_case WHERE id = 3;
INSERT INTO ebpf_audit_db_a2.identity_audit_case (id, k, c) VALUES (3, 60, 'tenant_a_proxy_db_a2_insert');
SELECT id, k, c FROM ebpf_audit_db_a2.identity_audit_case WHERE id = 3;
UPDATE ebpf_audit_db_a2.identity_audit_case SET k = 61, c = 'tenant_a_proxy_db_a2_update' WHERE id = 3;
DELETE FROM ebpf_audit_db_a2.identity_audit_case WHERE id = 3;
INSERT INTO ebpf_audit_db_b1.identity_audit_case (id, k, c) VALUES (1, 70, 'tenant_b_root_db_b1_insert');
SELECT id, k, c FROM ebpf_audit_db_b1.identity_audit_case WHERE id = 1;
UPDATE ebpf_audit_db_b1.identity_audit_case SET k = 71, c = 'tenant_b_root_db_b1_update' WHERE id = 1;
DELETE FROM ebpf_audit_db_b1.identity_audit_case WHERE id = 1;
INSERT INTO ebpf_audit_db_b2.identity_audit_case (id, k, c) VALUES (1, 80, 'tenant_b_root_db_b2_insert');
SELECT id, k, c FROM ebpf_audit_db_b2.identity_audit_case WHERE id = 1;
UPDATE ebpf_audit_db_b2.identity_audit_case SET k = 81, c = 'tenant_b_root_db_b2_update' WHERE id = 1;
DELETE FROM ebpf_audit_db_b2.identity_audit_case WHERE id = 1;
INSERT INTO ebpf_audit_db_b1.identity_audit_case (id, k, c) VALUES (2, 90, 'tenant_b_user_db_b1_insert');
SELECT id, k, c FROM ebpf_audit_db_b1.identity_audit_case WHERE id = 2;
UPDATE ebpf_audit_db_b1.identity_audit_case SET k = 91, c = 'tenant_b_user_db_b1_update' WHERE id = 2;
DELETE FROM ebpf_audit_db_b1.identity_audit_case WHERE id = 2;
INSERT INTO ebpf_audit_db_b2.identity_audit_case (id, k, c) VALUES (2, 100, 'tenant_b_user_db_b2_insert');
SELECT id, k, c FROM ebpf_audit_db_b2.identity_audit_case WHERE id = 2;
UPDATE ebpf_audit_db_b2.identity_audit_case SET k = 101, c = 'tenant_b_user_db_b2_update' WHERE id = 2;
DELETE FROM ebpf_audit_db_b2.identity_audit_case WHERE id = 2;
INSERT INTO ebpf_audit_db_b1.identity_audit_case (id, k, c) VALUES (3, 110, 'tenant_b_proxy_db_b1_insert');
SELECT id, k, c FROM ebpf_audit_db_b1.identity_audit_case WHERE id = 3;
UPDATE ebpf_audit_db_b1.identity_audit_case SET k = 111, c = 'tenant_b_proxy_db_b1_update' WHERE id = 3;
DELETE FROM ebpf_audit_db_b1.identity_audit_case WHERE id = 3;
INSERT INTO ebpf_audit_db_b2.identity_audit_case (id, k, c) VALUES (3, 120, 'tenant_b_proxy_db_b2_insert');
SELECT id, k, c FROM ebpf_audit_db_b2.identity_audit_case WHERE id = 3;
UPDATE ebpf_audit_db_b2.identity_audit_case SET k = 121, c = 'tenant_b_proxy_db_b2_update' WHERE id = 3;
DELETE FROM ebpf_audit_db_b2.identity_audit_case WHERE id = 3;
