# uprobe consumer config
# server_ip is written into each consumed event as ObAddr-format server_ip.
server_ip=7.27.43.145
agent_id=agent-7.27.43.145

collector_addr=7.27.43.138:50051
collector_discovery_enabled=true
collector_discovery_etcd_endpoints=http://7.27.43.139:2379
collector_discovery_service_name=audit-collector
collector_discovery_watch=true
collector_discovery_retry_interval_ms=3000
collector_discovery_selection_policy=hash_agent

collector_listen_addr=0.0.0.0:50051
collector_registry_enabled=true
collector_registry_etcd_endpoints=http://7.27.43.139:2379
collector_registry_service_name=audit-collector
collector_registry_instance_id=collector-1
collector_registry_advertise_addr=7.27.43.138:50051
collector_registry_lease_ttl_sec=10
collector_registry_keepalive_interval_sec=3

grpc_batch_bytes=262144 # 256KB
grpc_flush_interval_ms=1000
grpc_timeout_ms=2000

grpc_queue_bytes=16777216 # 16MB 
grpc_retry_initial_ms=100
grpc_retry_max_ms=500
